### ISSUE TITLE
Upgrade to current MediaWiki LTS

### ISSUE THREAD

**Issue by gjost** [denshoproject/encyc-mw#2]
We are currently using v1.24, which was EOL'd at the end of 2015.  Current LTS version is 1.31 which is good til June 2021.

MediaWiki Version lifecycle:  https://www.mediawiki.org/wiki/Version_lifecycle/en#Versions_and_their_end-of-life
Upgrading MediaWiki: https://www.mediawiki.org/wiki/Manual:Upgrading
MediaWiki on Debian/Ubuntu: https://www.mediawiki.org/wiki/Manual:Running_MediaWiki_on_Debian_or_Ubuntu

Note: running an out-of-date MediaWiki also affects `encyc-psms` and `encyc-core`.

Update: It would be nice to use the packaged MW in Debian.
- stretch (oldstable): 1:1.27.7-1
- stretch-backports: 1:1.31.2-1
- buster (stable): 1:1.31.6-1
OTOH our customizations may not get upgraded along with Debian.

**Comment by gjost** [comment]
Upgrade to each LTS version in turn

1.27 (https://www.mediawiki.org/wiki/MediaWiki_1.27)
- Requires php5.5.9+, php-mbstring/php7-mbstring
- Requires php openssl and mcrypt extensions


1.31 (https://www.mediawiki.org/wiki/MediaWiki_1.31)
- php7.0.0+
- Requires database schema updates
- Use at least version 1.31.1 (Nuke extension not included in 1.31.0)

**Comment by gjost** [comment]
Upgraded to MediaWiki 1.27 LTS in  `encyc-mw` dev branch commit `19d05995`.

**Comment by GeoffFroh** [comment]
Will need to run a stage/development instance, separate from current encyc production, in the colo for final integration testing.

**Comment by gjost** [comment]
Upgraded to MediaWiki 1.31 LTS in `encyc-mw` dev branch commit `9bf6e5f1`.
