### ISSUE TITLE
MW will not accept certain file types for upload

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/encyc-mw#4]
LocalSettings.php is not properly configured to accept several filetypes used in the `encyc-psms` app. 

`$wgFileExtensions` was not set correctly in LocalSettings.php after the MW upgrade. Compare config file on `master` at: https://github.com/denshoproject/encyc-mw/blob/master/conf/LocalSettings.php-1.24#L165

Reference: https://www.mediawiki.org/wiki/Manual:Configuring_file_uploads#Configuring_file_types

Related to: https://github.com/denshoproject/encyc-psms/issues/18

**Comment by gjost** [comment]
Fixed in `encyc-mw` commit `df72bec824` for upcoming package `encycmw-master_2.0.0~deb10_amd64`
